#!/usr/bin/env node
const {createReadStream, createWriteStream, chmodSync} = require('fs');
const {resolve} = require('path');
const filesDir = resolve('./built');
const webpack = require('webpack');
const webpackConfig = require('./webpack.config.js');
const {exec} = require('pkg');
const throwError = (message) => console.error('error:', message);
const compilationArgs = ['./dist/prepare-commit-msg.js', '--target', 'host', '--output', './dist/prepare-commit-msg', '--silent'];
const compileBinary = () => {
  const log = console.log;
  console.log = () => null;
  exec(compilationArgs, {silent: true});
  console.log = log;
}
const build = () => webpack(webpackConfig).run((err, stats) => err ? throwError('webpack build error') : compileBinary());
build()
