export interface EnvVars {
  GIT_JIRA_PASSWORD: 'GIT_JIRA_PASSWORD';
  GIT_JIRA_URL: 'GIT_JIRA_URL';
  GIT_JIRA_USER: 'GIT_JIRA_USER';
}

export const ENV_VARS: EnvVars = {
  GIT_JIRA_PASSWORD: 'GIT_JIRA_PASSWORD',
  GIT_JIRA_URL: 'GIT_JIRA_URL',
  GIT_JIRA_USER: 'GIT_JIRA_USER',
};
